import type { Report } from '@coinchecker/shared';
export const SAMPLE_REPORT: Report = {
  id: 'sample',
  chainId: '8453',
  address: '0x123456789012345678901234567890123456ABcD',
  name: 'Example Token',
  symbol: 'EXM',
  checkedAt: '2026-10-03T12:45:00Z',
  expiresAt: '2026-10-03T12:46:00Z',
  rulesVersion: '1.0.0',
  verdict: 'high',
  coverage: {
    label: 'partial',
    completed: 2,
    total: 6,
    limitations: ['Fictional report for exploring the interface. No token was scanned.'],
  },
  findings: [
    {
      id: 'selling',
      severity: 'high',
      title: 'Selling restrictions',
      explanation: 'Token cannot be sold on the example route.',
      limitations:
        'The exact affected callers and trading routes would need independent verification.',
      evidenceIds: ['sample:selling'],
    },
    {
      id: 'fee_control',
      severity: 'caution',
      title: 'Fee control',
      explanation: 'Administrator can change transfer fees.',
      limitations:
        'The current controlling role and its restrictions would need independent verification.',
      evidenceIds: ['sample:fees'],
    },
  ],
  evidence: [
    {
      id: 'sample:selling',
      source: 'goplus',
      field: 'cannot_sell_all',
      value: '1',
      observedAt: '2026-10-03T12:45:00Z',
      url: 'https://docs.gopluslabs.io/reference/response-details',
    },
    {
      id: 'sample:fees',
      source: 'goplus',
      field: 'slippage_modifiable',
      value: '1',
      observedAt: '2026-10-03T12:45:00Z',
      url: 'https://docs.gopluslabs.io/reference/response-details',
    },
  ],
  sources: [
    {
      source: 'goplus',
      status: 'ok',
      checkedAt: '2026-10-03T12:45:00Z',
      durationMs: 0,
      data: { cannot_sell_all: '1', slippage_modifiable: '1' },
      digest: 'Sample only',
    },
    {
      source: 'honeypot',
      status: 'partial',
      checkedAt: '2026-10-03T12:45:00Z',
      durationMs: 0,
      data: { simulationSuccess: false },
      digest: 'Sample only',
    },
    {
      source: 'dexscreener',
      status: 'ok',
      checkedAt: '2026-10-03T12:45:00Z',
      durationMs: 0,
      data: null,
      digest: 'Sample only',
    },
  ],
  pairs: [
    {
      address: '0x1234567890123456789012345678901234567890',
      dex: 'uniswap',
      label: 'EXM / WETH / Uniswap v2',
      url: 'https://dexscreener.com',
      priceUsd: 0.0042,
      priceChange24h: -2.8,
      liquidityUsd: 182000,
      volume24h: 23500,
      marketCap: null,
      fdv: 4200000,
      createdAt: '2026-10-01T08:00:00Z',
      baseSymbol: 'EXM',
      quoteSymbol: 'WETH',
    },
  ],
  selectedPair: null,
  contract: {
    verified: null,
    implementation: null,
    owner: null,
    isContract: null,
    deployedAt: null,
    creator: null,
    deploymentTx: null,
    audit: 'not_established',
    compiler: null,
  },
  history: [],
  historyCoverage: {
    fromBlock: null,
    toBlock: null,
    complete: false,
    note: 'Sample report. No on-chain history was fetched.',
  },
  project: {
    description: null,
    websites: [],
    repositories: [],
    logo: null,
    provenance: 'Sample only',
    prices: [
      [1, 0.005],
      [2, 0.0052],
      [3, 0.0049],
      [4, 0.0051],
      [5, 0.0048],
      [6, 0.0047],
      [7, 0.0049],
      [8, 0.0045],
      [9, 0.0046],
      [10, 0.0043],
      [11, 0.0044],
      [12, 0.0042],
    ],
  },
  metrics: {
    buyTax: null,
    sellTax: 18,
    holderCount: null,
    topHolderPercent: null,
    liquidityLockedPercent: null,
  },
};
SAMPLE_REPORT.selectedPair = SAMPLE_REPORT.pairs[0]!;
